### ISSUE TITLE
min/max ranges are not enforced

### ISSUE THREAD

**Issue by gurelcan** [cangurel90/uniswap_lp_roi#14]
Currently min/max ranges for user inputs in Final Values container (token1 price, token2 price, liq and vol) are not enforced

as far as i remember all were getting calculated correctly. 

ideally when an input is entered beyond min/max limit the input should be made equal to min/max limit. 

Following warnings could help user understand whats going on
for prices -> "Value can't deviate more than a factor of 10"
for vol and liq-> "Value can't deviate more than a factor of 5"

min limit on liquidity is especially important (has 2 conditions) since total liq can't be lower then invested amount

**Comment by fritzschoff** [comment]
will create big issue for tracking
