### ISSUE TITLE
Link to uniswap.info instead of etherscan

### ISSUE THREAD

**Issue by gurelcan** [cangurel90/uniswap_lp_roi#16]
<img width="486" alt="Screen Shot 2020-09-28 at 10 42 20" src="https://user-images.githubusercontent.com/25967697/94404223-509af280-0177-11eb-8b9f-69f49447f9bb.png">

it would be better if link pointed to uniswap.info instead of Etherscan

ex link for wbtc-eth https://uniswap.info/pair/0xbb2b8038a1640196fbe3e38816f3e67cba72d940

**Comment by fritzschoff** [comment]
ref in bigger issue
