### ISSUE TITLE
Use names of tokens on ROI Table 

### ISSUE THREAD

**Issue by gurelcan** [cangurel90/uniswap_lp_roi#17]
<img width="932" alt="Screen Shot 2020-09-28 at 10 46 56" src="https://user-images.githubusercontent.com/25967697/94404630-fe0e0600-0177-11eb-8ca4-e14ce6e8aa6c.png">

Can you replace HOLD Token and HODL Token2 with their respective names

**Comment by fritzschoff** [comment]
ref in big issue
