### ISSUE TITLE
MVP V1 - UI

### ISSUE THREAD

**Issue by gurelcan** [cangurel90/uniswap_lp_roi#19]
![1_Inital_look](https://user-images.githubusercontent.com/25967697/94682246-55a1a280-032d-11eb-8a3e-5f5e6808d9c6.JPG)
![2_pool_search_panel_1](https://user-images.githubusercontent.com/25967697/94682250-576b6600-032d-11eb-9349-67289da794dd.JPG)
![2_pool_search_panel_2](https://user-images.githubusercontent.com/25967697/94682251-5803fc80-032d-11eb-9802-a96560edd018.JPG)
![3_search_results_panel](https://user-images.githubusercontent.com/25967697/94682253-589c9300-032d-11eb-907f-569ce4cd4ce8.JPG)
![4_user_specification_panel](https://user-images.githubusercontent.com/25967697/94682254-59352980-032d-11eb-82cd-3cbb9931e952.JPG)
![5_ROI_table_panel_1](https://user-images.githubusercontent.com/25967697/94682257-59352980-032d-11eb-9124-7c8eae1478ef.JPG)
![6_ROI_table_panel_2](https://user-images.githubusercontent.com/25967697/94682258-59cdc000-032d-11eb-9fc4-bef1d218ac2e.JPG)

**Comment by gurelcan** [comment]
for toggle in Pool Search panel i feel like you might have an easier solution. Feel free to change it if you do

**Comment by gurelcan** [comment]
![sliders](https://user-images.githubusercontent.com/25967697/94718286-3705d080-035a-11eb-9eba-2296eb2fc3a1.gif)

for sliders can we use something like this?

**Comment by fritzschoff** [comment]
for the sliders, how should that work ? you got many steps between the possible range of liquidity figures

**Comment by gurelcan** [comment]
i was thinking something like          min....1/2x....1....2x....max  

but i see that it can be complicated

if so dont bother
