### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by gurelcan** [cangurel90/uniswap_lp_roi#6]
"Did not found any pool for the address" warning appears for no reason

**Comment by fritzschoff** [comment]
can't reproduce this issue, what where the steps you did before you get this warning?

**Comment by gurelcan** [comment]
can't recall either. will note it if it happens again

**Comment by gurelcan** [comment]
i see what the problem is now
The warning doesnt disappear
Try 0x55d5c232d921b9eaa6b37b5845e439acd04b4dba. This will result in warning
Then search 0x05cDe89cCfa0adA8C88D5A23caaa79Ef129E7883 this will the pool but the warning will remain

**Comment by fritzschoff** [comment]
alright, going to check it out!
